version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
